### ISSUE TITLE
Pequeña rotura con la section "about-me"

### ISSUE THREAD

**Issue by FacundoEG** [facuariasla/des-3#1]
Hola Facu! primero que todo te quiero felicitar por la pagina! la verdad que te quedo muy buena y cumple con todas las consignas del desafío! , pero te quiero corregir en una sola cosita que note.

Sabes que note que el contenedor del texto en la section "about-me" se estira por fuera del contenedor "second-box" aproximadamente a los 581px de ancho.
(abajo te dejo un screen)

![image](https://user-images.githubusercontent.com/79592789/124206177-3355d480-dab9-11eb-8f8c-7a5986fa8dc6.png)

Te recomendaría que le saques el height fijo que tiene, así toma el tamaño entero en relación al contenido y manejas los margenes con un padding. Tambíen podes usar el min-height y max-height. 

Te sugiero que veas eso, pero quédate tranquilo que es solo un detalle, en general la pagina quedo muy prolija!

Saludos!

**Comment by facuariasla** [comment]
Gracias facu por la devolución!
Ahi lo miro bien
